version: 2.1

orbs:
  codacy: codacy/base@10.2.2
  codacy_plugins_test: codacy/plugins-test@1.1.1

jobs:
  test_patterns:
    machine: true
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          command: |
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker run $CIRCLE_PROJECT_REPONAME:latest codacy_pylint_test.py
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
      - persist_to_workspace:
          paths:
            - docker-image.tar
          root: ~/workdir
workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version
      - codacy/sbt:
          name: generate_docs
          cmd: |
            sudo apt-get update
            sudo apt-get install -y pandoc
            sbt "doc-generator/run"
          requires:
            - codacy/checkout_and_version
          persist_to_workspace: true
      - test_patterns:
          requires:
            - generate_docs
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - test_patterns
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - codacy/publish_docker
