version: 2.1

orbs:
  codacy: codacy/base@1.0.0
  codacy_plugins_test: codacy/plugins-test@dev:0.6.0-fixpattern.4dacdfd

jobs:
  test_patterns:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: |
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker run $CIRCLE_PROJECT_REPONAME:latest codacy_pylint_test.py
            docker save --output ~/workdir/docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
      - persist_to_workspace:
          paths:
            - workdir/*
          root: ~/
workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version
      - test_patterns:
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - test_patterns
      - codacy/shell:
          name: publish_dockerhub
          context: CodacyDocker
          cmd: |
            docker load --input ~/workdir/docker-image.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:latest
            docker push codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker push codacy/$CIRCLE_PROJECT_REPONAME:latest
          requires:
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - publish_dockerhub
